### PR TITLE
feat: add gnome 3.36 support

### PR DESCRIPTION
**Pull request by oae**
Fixes for Gnome Shell 3.36 version. This **might break** in the older versions of Gnome Shell. I couldn't test it. We may need to add a bunch of if/else blocks to add support for older versions or we can just support only the latest Gnome Shell. What do you think @bigbn ?

### CODE REVIEW

**Comment by bigbn** [comment]
I think at least we must keep support of last stable debian release version of gnome. I'll try to check this changes on virtual machine.

**Comment by bigbn** [comment]
DebianBuster includes GNOME 3.30.
So we can drop everything earlier than 3.30

**Comment by bigbn** [comment]
Got this error under debian:

    Mar 08 16:53:05 debian gnome-software[14335]: State change on user/*/*/shell-extension/drop-down-terminal-x_bigbn.pro/* from installed to available is not OK
    Mar 08 16:53:05 debian gnome-shell[14100]: Extension "drop-down-terminal-x@bigbn.pro" had error: TypeError: Main.panel.connect is not a function
    Mar 08 16:53:05 debian gnome-software[14335]: State change on user/*/*/shell-extension/drop-down-terminal-x_bigbn.pro/* from available to installed is not OK
    Mar 08 16:53:05 debian gnome-software[14335]: drop-down-terminal-x_bigbn.pro has error: TypeError: Main.panel.connect is not a function

So it should be fixed before publishing a new version

**Comment by oae** [comment]
I will try this on a virtual machine when I have time.

**Pull request merged**
